### PR TITLE
Better constructor + remove use of extract()

### PR DESCRIPTION
**Pull request by innobrig**

### CODE REVIEW

**Comment by adbario** [comment]
Thanks for posting, valid points. How do you store your settings? Just asking because having them inside app container as a settings array is pretty standard.

There's a problem with this:

```
// If lifetime is string, convert it to timestamp
$lifetime = 0;
if (is_string($settings['lifetime'])) {
    $lifetime = strtotime($settings['lifetime']) - time();
}

// Set number of seconds after which data will be seen as garbage
if ($lifetime > 0) {
    ini_set('session.gc_maxlifetime', $lifetime);
}
```

This will set session cookie lifetime always to 0, if lifetime in settings is integer. So you need to change it to:

```
// If lifetime is string, convert it to timestamp
if (is_string($settings['lifetime'])) {
    $settings['lifetime'] = strtotime($settings['lifetime']) - time();
}

// Set number of seconds after which data will be seen as garbage
if ($settings['lifetime'] > 0) {
    ini_set('session.gc_maxlifetime', $settings['lifetime']);
}
```

Other changes coming probably soon:
- change lifetime from seconds to minutes, so no need to count the seconds
- remove session helper class injection to container, as this injection doesn't work for example with PHP-DI
- create a new setting boolean 'encrypt' to simply turn on/off the encryption without touching encryption key itself

**Comment by innobrig** [comment]
> > How do you store your settings? Just asking because having them inside app container as a settings array is pretty standard.

True, but in my case my settings.php is pretty extensive and I've opted to have sub-arrays for certain portions of functionality (session settings being one of them). So for me having the ability to pass a specific set/array of settings is essential. I think this feature makes sense because it gives you the option to use such a construct but doesn't detract from the original functionality. 

Thanks for your other points/corrections, I'll patch my version of the source. Do you want a new pull request for that or can you just fix that yourself? 

Thanks for providing this package, it's very useful.

**Comment by adbario** [comment]
> True, but in my case my settings.php is pretty extensive and I've opted to have sub-arrays for certain portions of functionality (session settings being one of them). So for me having the ability to pass a specific set/array of settings is essential. I think this feature makes sense because it gives you the option to use such a construct but doesn't detract from the original functionality.

That makes sense, but as I will remove container injection completely, there will be only settings array injected which can be located anywhere. Just inject the correct array and that's it.

> Do you want a new pull request for that or can you just fix that yourself?

Thanks for help, I'll be fixing things soon based on your comments and my own improvements.

> Thanks for providing this package, it's very useful.

You're very welcome and I'm very happy to get new ideas as well, so thanks for your support. Mostly I'm doing things for my own use, but happy to do modifications. Very simple but nice fix for Slims Twig-View is coming soon :)

**Comment by adbario** [comment]
Alright, made some changes now:
- removed container and helper class injection
- changed lifetime from seconds to minutes
- cleaned up code
- updated docs

**Pull request closed without merging**
